# Students' Marks Analysis Project

Description: This project analyzes marks of 50 students across 3 subjects using NumPy.
Includes total, average, highest, pass/fail stats, and more.


In [1]:
import numpy as np

In [2]:
students_marks = np.random.randint(101,size = (50,3))

total_marks=np.sum(students_marks, axis=1)

print("Total marks of each student:")
for i in total_marks:
    print(i)
    

Total marks of each student:
86
194
145
160
210
111
224
141
74
139
148
157
184
128
72
212
50
177
167
16
83
149
103
107
86
138
82
145
187
96
229
178
52
125
111
102
69
201
102
64
239
132
225
133
173
182
42
117
159
172


In [20]:
print("Average marks of each student:")
for i in total_marks:
    avg_mark = round(i/3,1)
    print(avg_mark)

Average marks of each student:
28.7
64.7
48.3
53.3
70.0
37.0
74.7
47.0
24.7
46.3
49.3
52.3
61.3
42.7
24.0
70.7
16.7
59.0
55.7
5.3
27.7
49.7
34.3
35.7
28.7
46.0
27.3
48.3
62.3
32.0
76.3
59.3
17.3
41.7
37.0
34.0
23.0
67.0
34.0
21.3
79.7
44.0
75.0
44.3
57.7
60.7
14.0
39.0
53.0
57.3


In [23]:
print("Highest score of each student:")
for row in students_marks: #accessing rows
    highest_mark = np.max(row) 
    print(highest_mark)

Highest score of each student:
48
89
52
78
87
69
81
80
51
83
92
85
79
90
29
81
20
95
95
6
46
89
70
69
38
77
44
87
76
76
100
73
28
63
41
61
51
99
52
28
99
96
99
92
98
66
22
87
98
95


In [24]:
print("Lowest score of each student:")
for row in students_marks:
    lowest_mark = np.min(row)
    print(lowest_mark)

Lowest score of each student:
4
38
42
13
42
14
70
19
4
22
13
21
51
5
20
52
13
40
23
4
8
17
7
13
15
8
13
2
35
2
51
36
8
17
31
2
8
19
1
9
43
13
29
7
6
53
5
5
11
35


In [31]:
print("average number in each subject:")
sum_of_subj = np.sum(students_marks, axis = 0)
avg_of_subj = sum_of_subj/50
print(avg_of_subj)

average number in each subject:
[49.42 40.3  45.84]


In [33]:
print("Maximum marks in each subject:")
for i in students_marks.T: #iterating thru each column of original array thru transpose
    print(max(i))

print("Minimum marks in each subject")
for i in students_marks.T: 
    print(min(i))

Maximum marks in each subject:
98
96
100
Minimum marks in each subject
2
5
1


In [32]:
print("No. of students with more than 90 marks:")
above90 = np.sum(np.any(students_marks>90,axis=1))
print(above90)

No. of students with more than 90 marks:
12


In [29]:
print("No. of students who passed all exams:")
passing_marks = 35
passed_stud = np.sum(np.all(students_marks>35,axis=1)) 
print(passed_stud)

print("No. of students who failed any exam:")
failed_stud = np.sum(np.any(students_marks<passing_marks,axis=1)) 
print(failed_stud)

No. of students who passed all exams:
11
No. of students who failed any exam:
37


In [10]:
print("TOP 5 students of the class:")
sorted_total=np.sort(total_marks)
top5=sorted_total[-1:-6:-1]
print(top5)

print("Bottom 5 students of the class:")
bottom5 = sorted_total[:5]
print(bottom5)

TOP 5 students of the class:
[239 229 225 224 212]
Bottom 5 students of the class:
[16 42 50 52 64]


In [35]:
print("No. of students scored less than 20 in maths(1st column)")
maths_score = students_marks[:,0]
below20 = np.sum(maths_score>20)
print(below20)

No. of students scored less than 85 in maths(1st column)
37


In [28]:
#SUMMARY
print("Student who topped the class has a total score:", max(total_marks))
print("The top students are:", top5)
print("Each subject averages:", avg_of_subj)
print("No. of students who passed all exams:",passed_stud)
print("No. of students who passed any exams:",failed_stud)

Student who topped the class has a total score: 239
The top students are: [239 229 225 224 212]
Each subject averages: [49.42 40.3  45.84]
No. of students who passed all exams: 11
No. of students who passed any exams: 37
